"""fix_user_table

Revision ID: deeb67b8d9d5
Revises: b0b0b1cfe2b9
Create Date: 2025-11-06 14:01:27.370290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'deeb67b8d9d5'
down_revision: Union[str, Sequence[str], None] = 'b0b0b1cfe2b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
